### ISSUE TITLE
增加一个新网站：linuxize.com

### ISSUE THREAD

**Issue by lkxed** [LCTT/lctt-scripts#87]
<img width="639" alt="image" src="https://user-images.githubusercontent.com/39257389/164172288-f94b5e66-c91e-427d-89dd-e43d9ceab1be.png">

**Comment by lujun9972** [comment]
我印象里之前有选这个网站的，后来不记得是因为质量不行还是什么问题没选了

**Comment by lkxed** [comment]
> 我印象里之前有选这个网站的，后来不记得是因为质量不行还是什么问题没选了

或许是质量问题...他家发的都是命令介绍和安装教程。
