### ISSUE TITLE
www.debugpoint.com 可以排除掉两个内容

### ISSUE THREAD

**Issue by lkxed** [LCTT/lctt-scripts#88]
1. `<hr>`  后紧跟着的 `<p>`，是他们网站的推广，可以用 `hr + p` 匹配到；还有再之后的 `<a>`，或许可以用 `hr + p + a`？
2. `.sharedaddy`，他们网站的社交网络分享。

**Comment by lkxed** [comment]
另外，这个网站的日期解析有问题，改成手动指定比较好。

我目前的方法是获取 `time[itemprop="datePublished"]` 的 `timestamp` 属性，然后格式化。

**Comment by lujun9972** [comment]
新的选题工具能支持不？能的话我把这个网站也停掉吧

**Comment by lkxed** [comment]
支持，好的，那也给我来选吧～
